/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Register a new user. The university is automatically inferred from the email domain.
         */
        post: operations["register_user_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login For Access Token
         * @description Standard OAuth2 login endpoint. Returns a JWT token and sets HTTPOnly cookie.
         */
        post: operations["login_for_access_token_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Users Me
         * @description Get the currently logged-in user's private profile.
         */
        get: operations["read_users_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User Me
         * @description Update the current user's profile (username, avatar).
         *     Only fields explicitly sent in the request body are updated.
         */
        patch: operations["update_user_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Password
         * @description Update the current user's password.
         */
        patch: operations["update_password_api_v1_users_me_password_patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read User Profile
         * @description Get the public profile of a specific user.
         */
        get: operations["read_user_profile_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Universities
         * @description List all registered universities.
         */
        get: operations["list_universities_api_v1_universities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/universities/{university_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get University
         * @description Get details of a specific university. Deep-linkable.
         */
        get: operations["get_university_api_v1_universities__university_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Communities
         * @description List communities within the user's university.
         */
        get: operations["list_communities_api_v1_communities_get"];
        put?: never;
        /**
         * Create Community
         * @description Create a new community. The user automatically becomes the owner and admin.
         */
        post: operations["create_community_api_v1_communities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Community
         * @description Get details of a specific community.
         */
        get: operations["get_community_api_v1_communities__community_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Community
         * @description Delete a community (Owner only).
         */
        delete: operations["delete_community_api_v1_communities__community_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Community
         * @description Update community settings (Admin only).
         */
        patch: operations["update_community_api_v1_communities__community_id__patch"];
        trace?: never;
    };
    "/api/v1/communities/{community_id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Community Posts
         * @description Get the feed of posts for a specific community. Highly efficient join load.
         *     Supports sorting by 'new' (default) or 'top'.
         */
        get: operations["get_community_posts_api_v1_communities__community_id__posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Community Members
         * @description List approved members of a community.
         *
         *     Security rules:
         *     - Public communities: any authenticated user can list members.
         *     - Request/invite communities: only approved members can list members.
         */
        get: operations["list_community_members_api_v1_communities__community_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Community
         * @description Join a community. Behavior depends on community type:
         *     - public  → instantly approved
         *     - request → answers to required questions are saved, status = pending
         *     - invite  → rejected with clear message (must use an invite link or direct invitation)
         */
        post: operations["join_community_api_v1_communities__community_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Leave Community
         * @description Leave a community.
         */
        post: operations["leave_community_api_v1_communities__community_id__leave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Community Admins
         * @description List all administrators of a community.
         *
         *     Security rules:
         *     - Public communities: any authenticated user can list admins.
         *     - Request/invite communities: only approved members or owner can list admins.
         */
        get: operations["list_community_admins_api_v1_communities__community_id__admins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfer Ownership
         * @description Transfer ownership of the community to another approved member. (Owner only).
         */
        post: operations["transfer_ownership_api_v1_communities__community_id__transfer_ownership_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Join Questions
         * @description List all join questions for a community (visible to all logged-in users so they can preview before joining).
         */
        get: operations["list_join_questions_api_v1_communities__community_id__questions_get"];
        put?: never;
        /**
         * Create Join Question
         * @description Add a join question to a community (Admin only).
         */
        post: operations["create_join_question_api_v1_communities__community_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Join Question
         * @description Delete a join question (Admin only).
         */
        delete: operations["delete_join_question_api_v1_communities__community_id__questions__question_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Join Question
         * @description Update a join question (Admin only).
         */
        patch: operations["update_join_question_api_v1_communities__community_id__questions__question_id__patch"];
        trace?: never;
    };
    "/api/v1/communities/{community_id}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Join Requests
         * @description List all pending join requests with their submitted answers.
         *     Returns user info + answers in one shot to avoid N+1 on the frontend.
         */
        get: operations["list_join_requests_api_v1_communities__community_id__requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/requests/{user_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Join Request
         * @description Approve a pending join request (Admin only).
         */
        post: operations["approve_join_request_api_v1_communities__community_id__requests__user_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/requests/{user_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Join Request
         * @description Reject and delete a pending join request + submitted answers (Admin only).
         */
        post: operations["reject_join_request_api_v1_communities__community_id__requests__user_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/invite-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invite Links
         * @description List all active invite links for a community (Admin only).
         */
        get: operations["list_invite_links_api_v1_communities__community_id__invite_links_get"];
        put?: never;
        /**
         * Create Invite Link
         * @description Generate a new invite link with optional expiry and max-use cap (Admin only).
         */
        post: operations["create_invite_link_api_v1_communities__community_id__invite_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/invite-links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Invite Link
         * @description Revoke and delete an invite link (Admin only).
         */
        delete: operations["delete_invite_link_api_v1_communities__community_id__invite_links__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Direct Invitation
         * @description Send a direct invitation to a user (Admin only).
         *     The invited user will see it in their notifications and can accept or decline.
         */
        post: operations["create_direct_invitation_api_v1_communities__community_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community_id}/members/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Member Role
         * @description Promote or demote a community member (Admin only).
         *     The owner of the community cannot be demoted.
         */
        patch: operations["update_member_role_api_v1_communities__community_id__members__user_id__role_patch"];
        trace?: never;
    };
    "/api/v1/invite/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Invite Link
         * @description Preview an invite link before accepting it.
         *     Used by the frontend to render the 'You've been invited to...' page.
         *     Does NOT consume the link.
         */
        get: operations["preview_invite_link_api_v1_invite__code__get"];
        put?: never;
        /**
         * Join Via Invite Link
         * @description Join a community using an invite link code.
         *     Validates expiry, max_uses, and duplicate membership before approving.
         */
        post: operations["join_via_invite_link_api_v1_invite__code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Invitations
         * @description List all pending invitations received by the current user.
         *     Used to populate the notifications bell in the frontend Navbar.
         */
        get: operations["list_my_invitations_api_v1_me_invitations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/invitations/{invite_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invitation
         * @description Accept a direct invitation. Instantly approves membership.
         */
        post: operations["accept_invitation_api_v1_me_invitations__invite_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/invitations/{invite_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline Invitation
         * @description Decline a direct invitation. Marks it as declined without adding the user to the community.
         */
        post: operations["decline_invitation_api_v1_me_invitations__invite_id__decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Global Feed
         * @description Get the global feed of posts for the current user's university.
         *     Supports sorting by 'new' (default) or 'top'.
         */
        get: operations["get_global_feed_api_v1_posts_get"];
        put?: never;
        /**
         * Create Post
         * @description Create a new post in a specific community.
         */
        post: operations["create_post_api_v1_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Post
         * @description Get a single post by its ID. Perfect for deep-linking.
         */
        get: operations["get_post_api_v1_posts__post_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Post
         * @description Delete a post (Author only).
         */
        delete: operations["delete_post_api_v1_posts__post_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Post
         * @description Update a post's content (Author only).
         */
        patch: operations["update_post_api_v1_posts__post_id__patch"];
        trace?: never;
    };
    "/api/v1/posts/{post_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vote Post
         * @description Upvote or downvote a post. Returns the updated post with the new score.
         */
        post: operations["vote_post_api_v1_posts__post_id__vote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global Search
         * @description Perform a global case-insensitive search (ILIKE) across users, communities, and posts.
         *     Results are limited to the user's university to maintain context.
         *     If 'type' is provided (e.g., 'users', 'communities', 'posts'), only that entity is queried.
         */
        get: operations["global_search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Presigned Url
         * @description Generate a presigned URL for uploading a file directly to MinIO.
         *     This avoids routing large file uploads through the FastAPI backend.
         */
        post: operations["get_presigned_url_api_v1_storage_presigned_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_for_access_token_api_v1_auth_login_post */
        Body_login_for_access_token_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * BucketName
         * @enum {string}
         */
        BucketName: "user-assets" | "community-assets" | "post-assets";
        /** CommunityCreate */
        CommunityCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** @default public */
            type: components["schemas"]["CommunityType"];
            /**
             * Allow Anonymous
             * @default false
             */
            allow_anonymous: boolean;
            /** Icon Key */
            icon_key?: string | null;
            /** Banner Key */
            banner_key?: string | null;
        };
        /** CommunityInvitationCreate */
        CommunityInvitationCreate: {
            /**
             * Invited User
             * Format: uuid
             */
            invited_user: string;
        };
        /** CommunityInvitationResponse */
        CommunityInvitationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            /**
             * Invited By
             * Format: uuid
             */
            invited_by: string;
            /**
             * Invited User
             * Format: uuid
             */
            invited_user: string;
            status: components["schemas"]["InvitationStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CommunityInviteLinkCreate */
        CommunityInviteLinkCreate: {
            /** Expires At */
            expires_at?: string | null;
            /** Max Uses */
            max_uses?: number | null;
        };
        /** CommunityInviteLinkResponse */
        CommunityInviteLinkResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Code */
            code: string;
            /** Expires At */
            expires_at: string | null;
            /** Max Uses */
            max_uses: number | null;
            /** Use Count */
            use_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CommunityJoinAnswerCreate */
        CommunityJoinAnswerCreate: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Answer */
            answer: string;
        };
        /** CommunityJoinAnswerResponse */
        CommunityJoinAnswerResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Answer */
            answer: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CommunityJoinQuestionCreate */
        CommunityJoinQuestionCreate: {
            /** Question */
            question: string;
            /**
             * Is Required
             * @default true
             */
            is_required: boolean;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
        };
        /** CommunityJoinQuestionResponse */
        CommunityJoinQuestionResponse: {
            /** Question */
            question: string;
            /**
             * Is Required
             * @default true
             */
            is_required: boolean;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
        };
        /** CommunityJoinQuestionUpdate */
        CommunityJoinQuestionUpdate: {
            /** Question */
            question?: string | null;
            /** Is Required */
            is_required?: boolean | null;
            /** Order Index */
            order_index?: number | null;
        };
        /**
         * CommunityJoinRequestSchema
         * @description Payload sent by the user when joining a community (especially type='request').
         */
        CommunityJoinRequestSchema: {
            /** Answers */
            answers?: components["schemas"]["CommunityJoinAnswerCreate"][] | null;
        };
        /** CommunityMemberResponse */
        CommunityMemberResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            status: components["schemas"]["MemberStatus"];
            /** Is Admin */
            is_admin: boolean;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /**
         * CommunityPublic
         * @description Schema used when embedding community data in posts or feeds.
         */
        CommunityPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Icon Key */
            icon_key: string | null;
            type: components["schemas"]["CommunityType"];
        };
        /** CommunityResponse */
        CommunityResponse: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** @default public */
            type: components["schemas"]["CommunityType"];
            /**
             * Allow Anonymous
             * @default false
             */
            allow_anonymous: boolean;
            /** Icon Key */
            icon_key?: string | null;
            /** Banner Key */
            banner_key?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * University Id
             * Format: uuid
             */
            university_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            user_membership_status?: components["schemas"]["MemberStatus"] | null;
        };
        /** CommunityRoleUpdate */
        CommunityRoleUpdate: {
            /** Is Admin */
            is_admin: boolean;
        };
        /**
         * CommunityType
         * @enum {string}
         */
        CommunityType: "public" | "request" | "invite";
        /** CommunityUpdate */
        CommunityUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            type?: components["schemas"]["CommunityType"] | null;
            /** Allow Anonymous */
            allow_anonymous?: boolean | null;
            /** Icon Key */
            icon_key?: string | null;
            /** Banner Key */
            banner_key?: string | null;
        };
        /** GlobalSearchResponse */
        GlobalSearchResponse: {
            /** Users */
            users: components["schemas"]["UserProfileResponse"][];
            /** Communities */
            communities: components["schemas"]["CommunityResponse"][];
            /** Posts */
            posts: components["schemas"]["PostFeedResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InvitationStatus
         * @enum {string}
         */
        InvitationStatus: "pending" | "accepted" | "declined";
        /**
         * InviteLinkPreviewResponse
         * @description Data sent to the frontend BEFORE a user clicks Join on an invite link.
         */
        InviteLinkPreviewResponse: {
            community: components["schemas"]["CommunityPublic"];
            /** Code */
            code: string;
            /** Expires At */
            expires_at: string | null;
        };
        /**
         * JoinRequestResponse
         * @description Data sent to the Admin when viewing pending join requests.
         */
        JoinRequestResponse: {
            user: components["schemas"]["UserPublic"];
            /** Answers */
            answers: components["schemas"]["CommunityJoinAnswerResponse"][];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
        };
        /**
         * MemberStatus
         * @enum {string}
         */
        MemberStatus: "pending" | "approved";
        /** PaginatedResponse[CommunityResponse] */
        PaginatedResponse_CommunityResponse_: {
            /** Items */
            items: components["schemas"]["CommunityResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PaginatedResponse[PostFeedResponse] */
        PaginatedResponse_PostFeedResponse_: {
            /** Items */
            items: components["schemas"]["PostFeedResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PaginatedResponse[UniversityResponse] */
        PaginatedResponse_UniversityResponse_: {
            /** Items */
            items: components["schemas"]["UniversityResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PaginatedResponse[UserPublic] */
        PaginatedResponse_UserPublic_: {
            /** Items */
            items: components["schemas"]["UserPublic"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PostCreate */
        PostCreate: {
            /** Title */
            title: string;
            /** Body */
            body?: string | null;
            /** Image Key */
            image_key?: string | null;
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            /**
             * Is Anonymous
             * @default false
             */
            is_anonymous: boolean;
        };
        /**
         * PostFeedResponse
         * @description Rich response schema used for feeds.
         *     Includes nested relationships to avoid N+1 queries on the frontend.
         */
        PostFeedResponse: {
            /** Title */
            title: string;
            /** Body */
            body?: string | null;
            /** Image Key */
            image_key?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            /** Author Id */
            author_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
            /** Is Anonymous */
            is_anonymous: boolean;
            author?: components["schemas"]["UserPublic"] | null;
            community: components["schemas"]["CommunityPublic"];
            /**
             * Score
             * @default 0
             */
            score: number;
            /** User Vote */
            user_vote?: number | null;
            /**
             * Comment Count
             * @default 0
             */
            comment_count: number;
        };
        /** PostResponse */
        PostResponse: {
            /** Title */
            title: string;
            /** Body */
            body?: string | null;
            /** Image Key */
            image_key?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            /** Author Id */
            author_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
            /** Is Anonymous */
            is_anonymous: boolean;
        };
        /** PostUpdate */
        PostUpdate: {
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /** Image Key */
            image_key?: string | null;
        };
        /** PresignedUrlRequest */
        PresignedUrlRequest: {
            bucket_name: components["schemas"]["BucketName"];
        };
        /** PresignedUrlResponse */
        PresignedUrlResponse: {
            /** Url */
            url: string;
            /** File Key */
            file_key: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** TransferOwnershipRequest */
        TransferOwnershipRequest: {
            /**
             * New Owner Id
             * Format: uuid
             */
            new_owner_id: string;
        };
        /** UniversityResponse */
        UniversityResponse: {
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** UserChangePassword */
        UserChangePassword: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserProfileResponse
         * @description Schema for viewing another user's profile (safe, no email).
         */
        UserProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Avatar Key */
            avatar_key: string | null;
            /**
             * University Id
             * Format: uuid
             */
            university_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserPublic
         * @description Schema used when embedding user data in posts, comments, etc.
         */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Avatar Key */
            avatar_key: string | null;
            /**
             * University Id
             * Format: uuid
             */
            university_id: string;
        };
        /**
         * UserResponse
         * @description Full user schema for the /users/me endpoint (includes private data).
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Avatar Key */
            avatar_key: string | null;
            /**
             * University Id
             * Format: uuid
             */
            university_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * UserUpdateProfile
         * @description Only for updating non-critical profile info.
         */
        UserUpdateProfile: {
            /** Username */
            username?: string | null;
            /** Avatar Key */
            avatar_key?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoteCreate */
        VoteCreate: {
            /** Value */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_user_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_for_access_token_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_users_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_user_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_password_api_v1_users_me_password_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserChangePassword"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_user_profile_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_universities_api_v1_universities_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_UniversityResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_university_api_v1_universities__university_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_communities_api_v1_communities_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_CommunityResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_community_api_v1_communities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_community_api_v1_communities__community_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_community_api_v1_communities__community_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_community_api_v1_communities__community_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_community_posts_api_v1_communities__community_id__posts_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_PostFeedResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_community_members_api_v1_communities__community_id__members_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_UserPublic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_community_api_v1_communities__community_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommunityJoinRequestSchema"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_community_api_v1_communities__community_id__leave_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_community_admins_api_v1_communities__community_id__admins_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_ownership_api_v1_communities__community_id__transfer_ownership_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnershipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_join_questions_api_v1_communities__community_id__questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityJoinQuestionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_join_question_api_v1_communities__community_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunityJoinQuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityJoinQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_join_question_api_v1_communities__community_id__questions__question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_join_question_api_v1_communities__community_id__questions__question_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunityJoinQuestionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityJoinQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_join_requests_api_v1_communities__community_id__requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequestResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_join_request_api_v1_communities__community_id__requests__user_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_join_request_api_v1_communities__community_id__requests__user_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invite_links_api_v1_communities__community_id__invite_links_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityInviteLinkResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_link_api_v1_communities__community_id__invite_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunityInviteLinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityInviteLinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_invite_link_api_v1_communities__community_id__invite_links__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_direct_invitation_api_v1_communities__community_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunityInvitationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityInvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_role_api_v1_communities__community_id__members__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunityRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_invite_link_api_v1_invite__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteLinkPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_via_invite_link_api_v1_invite__code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_invitations_api_v1_me_invitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityInvitationResponse"][];
                };
            };
        };
    };
    accept_invitation_api_v1_me_invitations__invite_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_invitation_api_v1_me_invitations__invite_id__decline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_global_feed_api_v1_posts_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_PostFeedResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_v1_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_api_v1_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostFeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_v1_posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_post_api_v1_posts__post_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vote_post_api_v1_posts__post_id__vote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostFeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    global_search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_presigned_url_api_v1_storage_presigned_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignedUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
